export const Category = {
    ENVIRONMENT: 'ENVIRONMENT',
    HEALTH: 'HEALTH',
    MENTAL_HEALTH: 'MENTAL HEALTH',
    ANIMAL_WELFARE: 'ANIMAL WELFARE',
    EDUCATION: 'EDUCATION',
    SOCIAL_SERVICES: 'SOCIAL SERVICES'
}